<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="manishs-MacBook-Air.local" failures="1" tests="13" name="Default test" time="14.973" errors="0" timestamp="6 Mar 2021 05:48:53 GMT">
  <testcase classname="TestAPIs.TestNG_DataProvider" name="POSTExample1" time="5.223"/>
  <testcase classname="TestAPIs.TestNG_DataProvider" name="POSTExample2" time="2.186"/>
  <testcase classname="TestAPIs.TestNG_DataProvider" name="POSTExample2" time="1.171"/>
  <testcase classname="TestAPIs.TestNG_DataProvider" name="POSTExample2" time="0.92"/>
  <testcase classname="TestAPIs.TestNG_DataProvider" name="POSTExample2" time="1.26"/>
  <testcase classname="TestAPIs.TestNG_DataProvider" name="POSTExample2" time="0.914"/>
  <testcase classname="TestAPIs.POST_Tests" name="postdata" time="0.51"/>
  <testcase classname="TestAPIs.POST_Tests" name="postdata" time="0.095"/>
  <testcase classname="TestAPIs.POST_Tests" name="postdata" time="0.076"/>
  <testcase classname="ObjectMapper" name="POSTCall1" time="0.346">
    <failure type="java.lang.AssertionError" message="expected [201] but found [500]">
      <![CDATA[java.lang.AssertionError: expected [201] but found [500]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:494)
	at org.testng.Assert.assertEquals(Assert.java:123)
	at org.testng.Assert.assertEquals(Assert.java:370)
	at org.testng.Assert.assertEquals(Assert.java:380)
	at ObjectMapper.POSTCall1(ObjectMapper.java:37)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:64)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:80)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1198)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1123)
	at org.testng.TestNG.run(TestNG.java:1031)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- POSTCall1 -->
  <testcase classname="TestAPIs.GETCall" name="POSTTest" time="1.637"/>
  <testcase classname="TestAPIs.GETCall" name="getcalltest" time="0.473"/>
  <testcase classname="TestAPIs.POST_Tests" name="getRecords" time="0.071"/>
</testsuite> <!-- Default test -->
